title       = "obis"
baseURL     = "https://obis-cli.tamnd.com/"
description = "A command line for obis."
contentDir  = "content"
outputDir   = "public"
theme       = "tago-doks"
syntaxHighlight = "true"

[params]
github = "https://github.com/tamnd/obis-cli"
